# Generated by Django 6.0.1 on 2026-02-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMTPSetting',
        ),
    ]
