# Generated by Django 5.2.5 on 2026-01-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accepted_terms',
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(blank=True, choices=[('create_account', 'Create Account'), ('reset_password', 'Reset Password'), ('login', 'Login'), ('delete_account', 'Delete Account'), ('update_email', 'Update Email'), ('verify_email', 'Verify Email')], max_length=50, null=True),
        ),
    ]
